#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

# gremote
# Creates a remote git repository from the current local directory

# Configuration
echo -n "Github Username:"
read user
echo

repo=${PWD##*/} # Actual dir
echo -n $repo

clone_url=https://github.com/${user}/${repo}.git

echo "------------------------------------------"
echo "----- Building New Github Repository -----"
echo "------------------------------------------"

# Setup remote repository
echo "--"
echo "-- Creating bare remote repository at:"
echo "-- $clone_url"
echo "--"

curl -u ${user} https://api.github.com/user/repos -d "{\"name\": \"${repo}\"}"

# Configure local repository
echo "--"
echo "-- Initializing local repository & pushing to remote"
echo "--"

echo "1) touch .gitignore"
touch .gitignore
echo "2) git init"
git init
echo "3) git add ."
git add .
echo "4) git commit -m 'initial commit'"
git commit -m 'initial commit' || true
echo "5) git push --all $clone_url"
git push --all $clone_url
echo "6) git remote add origin $clone_url"
git remote add origin $clone_url || true
echo "7) git config branch.master.remote origin"
git config branch.master.remote origin
echo "8) git config branch.master.merge refs/heads/master"
git config branch.master.merge refs/heads/master
echo "9) git fetch"
git fetch
echo "10) git merge master"
git merge master
echo "11) git branch -a"
git branch -a

echo "--"
echo "-- Your new git repository '$repo' is ready and initialized at:"
echo "-- $clone_url"
echo "--"
